language: node_js
node_js:
    - "node"
install: true
script: echo "Skipping build"
deploy:
  edge: true
  provider: bluemixcloudfoundry
  username: apikey
  organization: perttu.savolainen+ibmcloud@nordcloud.com
  space: dev
  manifest: manifest.yml